# Site settings
title: Pixel y Pincel
email: hola@pixelypincel.es
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pixelypincel.es" # the base hostname & protocol for your site


twitter_username: pixelypincel
instagram_username: pixelypincel
facebook_username: pixelypincel
youtube_username: pixelypincel

# Build settings
markdown: kramdown

collections:
  talleres:
    output: true
    permalink: /:collection/:path/
